### ISSUE TITLE
Rust thread panicked

### ISSUE THREAD

**Issue by khipukamayuq** [anowell/mia#24]
Hi,

I'm on Ubuntu 18.10 using Terminator, z-shell w/ oh-my-zsh. New algorithmia-cli installation went smoothly, was able to setup auth without issue. Then `algo run` of tutorial and "hello world" resulted in Rust thread panic. Same result for `ls`, `mkdir`; any command besides `auth` or `--help` Ran rust's suggested backtrace and got:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:323
stack backtrace:
   1:     0x562160252fdc - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x562160258f6e - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x562160258b74 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x56216025940b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x5621602592a4 - std::panicking::begin_panic::hd6eb68e27bdf6140
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x5621602591c9 - std::panicking::begin_panic_fmt::hfea5965948b877f8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x562160259157 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x562160285f0d - core::panicking::panic_fmt::hc0f6d7b2c300cdd9
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x562160285e44 - core::panicking::panic::h7abeb5b818ec354e
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:     0x56215ff4a6b5 - algo::algo::display_response::h64b45ed097c40b87
  11:     0x56215ff5b59b - algo::run::h15d77e9bbe379ff0
  12:     0x56215ff54676 - algo::main::hebe37476801212aa
  13:     0x5621602603da - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  14:     0x562160259b76 - std::rt::lang_start::hd7c880a37a646e81
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/rt.rs:57
  15:     0x7f310c1cc09a - __libc_start_main
  16:     0x56215ff09d28 - <unknown>
```
Found a github repo for a rust-buildbot like the above reference, but it's deprecated; couldn't be the same one as above? Either way, not sure how I broke this or how to tackle a fix. Thanks in advance for any help.

**Comment by anowell** [comment]
Thanks for the issue report. I believe it's panicking for lack of finding the system's terminfo database which could be missing from our documentation or setup. I'll try and repo the issue to verify shortly, but if that's the case, it might just be a matter of installing the `ncurses-term` package.

**Comment by munikarmanish** [comment]
I'm also experiencing this issue on Ubuntu 19.10. Any updates on this? @anowell

**Comment by saintaardvark** [comment]
I had what looks like the same problem, with Rust panicking on every invocation of `algo` I tried.  Setting the `TERM` environment variable to `xterm` appears to have done the trick, though:

```
6:46 $ echo $TERM; algo ls
xterm-256color
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
16:46 $ TERM=xterm algo ls
saintaardvark  
```
